### ISSUE TITLE
percircle objects are not loaded after refreshing page

### ISSUE THREAD

**Issue by toubou91** [toubou91/percircle#13]
Here are the console's logs:

<code>ReferenceError: jQuery is not defined</code>
<code>ReferenceError: $ is not defined</code>

**Comment by chrisahardie** [comment]
That's an odd bug... I can't repro locally after having just pulled down the latest. Any chance you were without connectivity and may have been using a cached version until you refreshed?

**Comment by toubou91** [comment]
@chrisahardie indeed.

Hmmm, seems like the problem is gone. Magically!.
Let's close this for now.
