### ISSUE TITLE
Could you update bower version to the latest?

### ISSUE THREAD

**Issue by tinglu** [toubou91/percircle#29]

**Comment by toubou91** [comment]
Hey @tinglu , thanks for this one, sure, but unfortunately, lately I'm a bit busy, which means I am not sure if I can find some time in the weekend.
Nonetheless, if you need it asap, feel free for a PR :smiley:

**Comment by tinglu** [comment]
Hi @toubou91 correct me if I'm wrong but could you publish a new release of 1.0.11 so the bower package would become the latest one? :)

**Comment by toubou91** [comment]
Hey @tinglu , oh yes, sorry, it was only pushed in the project's npm repo.
Could you please check now and let me know?

**Comment by tinglu** [comment]
Perfect thank you.
