### ISSUE TITLE
Provide better color support and a more abstract way of defining percircle colors.

### ISSUE THREAD

**Issue by toubou91** [toubou91/percircle#3]
Currently, there are only specific colors supported from percircle. Future implementations should provide a more abstract way of defining colors (maybe without even having to declare their definitions in the <code>css</code>).

**Comment by wboka** [comment]
Suggestion: he user could pass a data attribute, "data-color", which would need to be a valid css color declaration and pass that to the setup of the percircle in JavaScript.

**Comment by toubou91** [comment]
Hey @wboka ,

yes, it seems that #17 leads the way to using html data attributes.
For more details according to this implementation, <a href="https://github.com/toubou91/percircle/pull/17#issuecomment-152780982">this</a> is what I'm currently thinking of.
