### ISSUE TITLE
Enhancement: Support decimals in [data-percentage] attribute

### ISSUE THREAD

**Issue by MaikelNait** [toubou91/percircle#37]
Is it possible to support decimals on the data percentage?  e.g  [51.4%]
There is no mention in the documentation ...

**Comment by toubou91** [comment]
Hey @MaikelNait ,

thank you for your question/proposal.
Yes, it's possible, either as a data attribute as you fore-mentioned:

```
<div id="custom-color" class="big" data-percent="99.5"></div>
```
or as jQuery parameter:

```
$("#custom-color").percircle({
	percent: 64.5
});
```

However, I will leave the issue open for now, until I add a brief mention regarding decimal support on percentages.

Thank you!

**Comment by MaikelNait** [comment]
Thanks a lot !   ☺

Miguel
