### ISSUE TITLE
strict mode does not allow function declarations in a lexically nested statement

### ISSUE THREAD

**Issue by tinglu** [toubou91/percircle#38]
The latest merge has JavaScript error.
You must not put a function declaration inside any other block.
<img width="1003" alt="screen shot 2016-08-21 at 15 21 18" src="https://cloud.githubusercontent.com/assets/1032258/17835510/520ae5c4-67b3-11e6-9a75-98d2a3100567.png">

**Comment by toubou91** [comment]
Also take into account the following comment, when about to fix this issue:

> Don't use setInterval to update styles, use requestAnimationFrame, and setTimeout(fn, 0) doesn't necessarily ensure that the animation will occur. take a look at [this ](https://stackoverflow.com/questions/38553329/remove-css-transition-move-the-element-then-re-apply-it-before-moving-it-again)
