### ISSUE TITLE
How to change the percentage value dynamically?

### ISSUE THREAD

**Issue by twob-shahid** [toubou91/percircle#42]
How to change the percentage value dynamically?

**Comment by toubou91** [comment]
Hello @twob-shahid ,

thanks for using percircle.
My greatest apologies for [having been not able to investigate your query earlier]( #43  ) .

The requirement you asked for, is not currently available, but I would be happy to review a pull request for it.

Thanks,
TB

**Comment by toubou91** [comment]
Hey @twob-shahid ,

as you can see, your request is not done!
Please update to v1.0.24!

_You can check the updated documentation on how to achieve updating the value of the a percircle object dynamically._
