### ISSUE TITLE
Problem in update value dynamically

### ISSUE THREAD

**Issue by parveenvinove** [toubou91/percircle#48]
Hi,

Getting issue when i update dynamically value less than to previous (For example : 51 ->20), Than circle not work on clockwise.

Can you please provide me solution.

Thanks

**Comment by toubou91** [comment]
Hey,

thanks a lot for using percircle!

Things are hectic lately, so I hope I can take a look at the end of the week.
Otherwise, I will be really happy to review a PR of yours :smiley: 

_In any case, if this is a bug, it should be somehow related to #45 ._

**Comment by toubou91** [comment]
Hey,

thanks a lot for using percircle!

Things are hectic here lately, so, I don't think I currently have the time capacity to look at this issue.
I would be really happy, though, to review a PR of yours :smiley: 

_In any case, if this is a bug, it should be somehow related to #45 ._

**Comment by parveenvinove** [comment]
Hi,

Thank you so much for reply.
Let me know when you done this issue, because i think it is big issue.

**Comment by toubou91** [comment]
Hi @parveenvinove ,

I found a few minutes to provide a quick fix for the issue you introduced.
This should now be fixed with v1.0.26

Thanks for using percircle :bowtie: !

- Thodoris
